// @ts-nocheck
"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useEffect, useMemo, useState } from "react";
import ProductNav from "../../components/ProductNav";
import LedgerAssistant from "../../components/LedgerAssistant";
import { calculate, Expense, getGroup, Group, groupTypes, saveGroup } from "../../lib/groups";

export default function GroupWorkspace(){
 const {id}=useParams<{id:string}>(); const [group,setGroup]=useState<Group|null>(null); const [showAdd,setShowAdd]=useState(false); const [tab,setTab]=useState("overview");
 useEffect(()=>setGroup(getGroup(id)),[id]);
 const stats=useMemo(()=>group?calculate(group):null,[group]); if(!group||!stats)return <><ProductNav/><main className="app-page"><div className="loading-card">Loading your group…</div></main></>;
 const member=(memberId:string)=>group.members.find(m=>m.id===memberId);
 function addExpense(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const participants=data.getAll("participants") as string[];const expense:Expense={id:Date.now().toString(36),title:String(data.get("title")),amount:Number(data.get("amount")),paidBy:String(data.get("paidBy")),participants:participants.length?participants:group.members.map(m=>m.id),date:"Today",category:String(data.get("category"))};const updated={...group,expenses:[expense,...group.expenses]};setGroup(updated);saveGroup(updated);setShowAdd(false);}
 const kind=groupTypes.find(item=>item.id===group.type);
 return <><ProductNav/><main className="app-page wide page-enter"><div className="group-hero"><Link href="/groups" className="back-link">← All groups</Link><div className="group-title"><span className="group-icon large-icon">{kind?.icon}</span><div><span className="step-label">{kind?.title}</span><h1>{group.name}</h1><p>{group.members.length} people · {group.expenses.length} expenses</p></div><button className="primary" onClick={()=>setShowAdd(true)}>+ Add expense</button></div><div className="face-row big">{group.members.map(m=><i key={m.id} style={{background:m.color}}>{m.name.charAt(0)}</i>)}</div></div>
 <div className="tab-bar">{["overview","expenses","balances","activity"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item.charAt(0).toUpperCase()+item.slice(1)}</button>)}</div>
 {tab==="overview"&&<><div className="summary-grid"><article><small>TOTAL GROUP SPEND</small><strong>{group.currency}{stats.total.toFixed(2)}</strong><span>Across {group.expenses.length} expenses</span></article><article><small>YOU ARE {stats.balances[group.members[0].id]>=0?"OWED":"OWING"}</small><strong className={stats.balances[group.members[0].id]>=0?"positive":"negative"}>{group.currency}{Math.abs(stats.balances[group.members[0].id]).toFixed(2)}</strong><span>Paid {group.currency}{stats.paid[group.members[0].id].toFixed(2)} · Share {group.currency}{stats.share[group.members[0].id].toFixed(2)}</span></article><article className="violet-card"><small>PAYMENTS NEEDED</small><strong>{stats.settlements.length}</strong><span>OweZero found the shortest path</span></article></div><div className="workspace-grid"><section className="panel"><div className="panel-head"><div><span className="step-label">RECENT EXPENSES</span><h2>What the group spent</h2></div><button onClick={()=>setTab("expenses")}>View all</button></div>{group.expenses.length?group.expenses.slice(0,4).map(e=><ExpenseRow key={e.id} expense={e} group={group}/>):<EmptyExpenses onAdd={()=>setShowAdd(true)}/>}</section><section className="panel settle-preview"><div className="panel-head"><div><span className="step-label">SETTLEMENT PLAN</span><h2>Who pays whom</h2></div></div>{stats.settlements.length?stats.settlements.slice(0,3).map(s=><div className="mini-settlement" key={s.id}><i style={{background:member(s.from)?.color}}>{member(s.from)?.name.charAt(0)}</i><span><b>{member(s.from)?.name}</b><small>pays {member(s.to)?.name}</small></span><strong>{group.currency}{s.amount.toFixed(2)}</strong></div>):<div className="all-clear">✓<b>Everyone is even</b><span>No payments needed.</span></div>}<Link className="primary full" href={`/settle/${group.id}`}>Open settlement plan →</Link></section></div><LedgerAssistant group={group}/></>}
 {tab==="expenses"&&<section className="panel single-panel"><div className="panel-head"><div><span className="step-label">ALL EXPENSES</span><h2>{group.expenses.length} group expenses</h2></div><button className="primary small" onClick={()=>setShowAdd(true)}>+ Add expense</button></div>{group.expenses.length?group.expenses.map(e=><ExpenseRow key={e.id} expense={e} group={group}/>):<EmptyExpenses onAdd={()=>setShowAdd(true)}/>}</section>}
 {tab==="balances"&&<section className="panel single-panel"><div className="panel-head"><div><span className="step-label">CLEAR, EXPLAINABLE MATH</span><h2>Everyone's balance</h2></div></div>{group.members.map(m=><div className="balance-row detailed" key={m.id}><i style={{background:m.color}}>{m.name.charAt(0)}</i><div><b>{m.name}</b><small>Paid {group.currency}{stats.paid[m.id].toFixed(2)} · Fair share {group.currency}{stats.share[m.id].toFixed(2)}</small></div><strong className={stats.balances[m.id]>=0?"positive":"negative"}>{stats.balances[m.id]>=0?"+":"−"}{group.currency}{Math.abs(stats.balances[m.id]).toFixed(2)}</strong></div>)}<Link className="primary settle-link" href={`/settle/${group.id}`}>Settle this group →</Link></section>}
 {tab==="activity"&&<section className="panel single-panel"><div className="panel-head"><div><span className="step-label">GROUP HISTORY</span><h2>Everything that happened</h2></div></div>{group.expenses.map((e,index)=><div className="activity-row" key={e.id}><span className="activity-dot"/><div><b>{member(e.paidBy)?.name} added “{e.title}”</b><small>{e.date} · split with {e.participants.length} people</small></div><strong>{group.currency}{e.amount.toFixed(2)}</strong>{index<group.expenses.length-1&&<i/>}</div>)}</section>}
 </main>{showAdd&&<div className="modal-backdrop" onMouseDown={()=>setShowAdd(false)}><form className="expense-modal" onSubmit={addExpense} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setShowAdd(false)}>×</button><span className="step-label">NEW EXPENSE</span><h2>What did someone pay for?</h2><label>Description<input required name="title" autoFocus placeholder="e.g. Dinner at Nando's"/></label><div className="form-two"><label>Amount<input required min="0.01" step="0.01" name="amount" type="number" placeholder="0.00"/></label><label>Category<select name="category"><option>Food</option><option>Travel</option><option>Stay</option><option>Groceries</option><option>Other</option></select></label></div><label>Paid by<select name="paidBy">{group.members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><fieldset><legend>Split with</legend><div className="participant-grid">{group.members.map(m=><label key={m.id}><input defaultChecked type="checkbox" name="participants" value={m.id}/><span style={{background:m.color}}>{m.name.charAt(0)}</span>{m.name}</label>)}</div></fieldset><button className="primary full">Add expense →</button></form></div>}</>;
}
function ExpenseRow({expense,group}:{expense:Expense;group:Group}){const payer=group.members.find(m=>m.id===expense.paidBy);return <div className="expense-row"><span className="expense-icon">{expense.category==="Food"?"♨":expense.category==="Travel"?"✈":expense.category==="Stay"?"⌂":"◇"}</span><div><b>{expense.title}</b><small>{payer?.name} paid · {expense.date} · {expense.participants.length} people</small></div><strong>{group.currency}{expense.amount.toFixed(2)}</strong></div>}
function EmptyExpenses({onAdd}:{onAdd:()=>void}){return <div className="empty-state"><span>＋</span><h3>No expenses yet</h3><p>Add the first shared cost and OweZero will calculate everything.</p><button className="primary" onClick={onAdd}>Add an expense</button></div>}
